class _BotCommands:
    def __init__(self):
        self.StartCommand = 'mulai'
        self.MirrorCommand = 'koco'
        self.UnzipMirrorCommand = 'unzipkoco'
        self.TarMirrorCommand = 'tarkoco'
        self.ZipMirrorCommand = 'zipmirror'
        self.CancelMirror = 'batal'
        self.CancelAllCommand = 'gagal'
        self.ListCommand = 'list'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'cok'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'tolong'
        self.LogCommand = 'log'
        self.SpeedCommand = 'gass'
        self.CloneCommand = 'kelon'
        self.CountCommand = 'count'
        self.WatchCommand = 'nonton'
        self.TarWatchCommand = 'tarnonton'
        self.DeleteCommand = 'del'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'
        self.UsageCommand = 'usage'

BotCommands = _BotCommands()
